version: '3'

services:
  geoip.tech:
    build: https://github.com/zulhilmizainuddin/geoip-webservice.git
    container_name: geoip.tech
    ports:
      - 4000:4000
  georoute.tech:
    build: https://github.com/zulhilmizainuddin/georoute.git
    container_name: georoute.tech
    ports:
      - 3000:3000
  proxy:
    build: https://github.com/zulhilmizainuddin/georoute-proxy.git
    container_name: proxy
    ports:
      - 80:80
